FROM ubuntu:18.04 AS builder

ARG HUGO_VERSION=0.45.1

RUN apt update && apt install -y wget ca-certificates
RUN wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
RUN tar xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo

FROM scratch

COPY --from=builder /hugo /hugo

ENTRYPOINT ["/hugo"]
